export const ADD_SEARCH_ENTRY = 'REQUEST_GISTS';

export const SET_GISTS_RESOLVED = 'SET_GISTS_RESOLVED';
export const SET_GISTS_FAILED = 'SET_GISTS_FAILED';

export const SET_GIST_FORKS_RESOLVED = 'SET_GIST_FORKS_RESOLVED';
export const SET_GIST_FORKS_FAILED = 'SET_GIST_FORKS_FAILED';
