
export enum Constants {
    REQUEST_GISTS = 'REQUEST_GISTS',
    SET_GISTS = 'SET_GISTS',
    SET_GIST_FORKS = 'SET_GISTS_FORKS',
    SET_GISTS_RESOLVED = 'SET_GISTS_RESOLVED',
    SET_GISTS_FAILED = 'SET_GISTS_FAILED',
    SET_SEARCH_QUEUE = 'SET_SEARCH_QUEUE'
}
